# python3
# Ultimate OZIP Toolkit - Decrypt, Extract & Firmware Zip Creator
import os
import sys
import zipfile
from Cryptodome.Cipher import AES

# Master list of Oppo/Realme AES Keys
KEYS = [
    "D6DCCF0AD5ACD4E0292E522DB7C1381E", # Realme X, XT, 3 Pro, R9s
    "1C4C1EA3A12531AE491B21BB31613C11", # Realme 5 Pro, Q
    "1C4A11A3A12589AE441A23BB31517733", # Realme X2
    "1C4A11A3A12513AE441B23BB31513121", # Reno 2
    "D6EECF0AE5ACD4E0E9FE522DE7CE381E", 
    "D6ECCF0AE5ACD4E0E92E522DE7C1381E", 
]

def create_firmware_zip(zip_path):
    print("\n[+] Creating Custom Firmware-Only Flashable ZIP...")
    fw_zip_path = zip_path.replace(".zip", "_FIRMWARE_ONLY.zip")
    
    try:
        with zipfile.ZipFile(zip_path, 'r') as z_in, zipfile.ZipFile(fw_zip_path, 'w', zipfile.ZIP_DEFLATED) as z_out:
            fw_files = [f for f in z_in.namelist() if f.startswith("firmware-update/")]
            if not fw_files:
                print("[-] No firmware-update folder found. Cannot create firmware zip.")
                return

            print("    -> Copying base partitions (modem, xbl, tz, etc.)...")
            for f in fw_files:
                z_out.writestr(f, z_in.read(f))
                
            bin_path = "META-INF/com/google/android/update-binary"
            if bin_path in z_in.namelist():
                z_out.writestr(bin_path, z_in.read(bin_path))
                
            script_path = "META-INF/com/google/android/updater-script"
            if script_path in z_in.namelist():
                print("    -> Generating smart updater-script...")
                orig_script = z_in.read(script_path).decode('utf-8')
                new_script = [
                    'ui_print("=================================");',
                    'ui_print("  Realme X Custom Firmware Zip   ");',
                    'ui_print("  Generated by Ultimate Toolkit  ");',
                    'ui_print("=================================");',
                    'ui_print("Flashing base firmware...");'
                ]
                
                # Intelligently grab ONLY the commands that flash firmware files
                for line in orig_script.split('\n'):
                    line = line.strip()
                    if "firmware-update/" in line and "package_extract_file" in line:
                        new_script.append(line)
                
                new_script.append('ui_print("Firmware flashed successfully!");')
                z_out.writestr(script_path, '\n'.join(new_script))
                
        print(f"[SUCCESS] Firmware ZIP created: {os.path.basename(fw_zip_path)}")
    except Exception as e:
        print(f"[-] Error creating firmware zip: {e}")

def extract_zip(zip_path):
    choice = input("\n[?] Do you want to extract the FULL decrypted ZIP to a folder? (y/N): ").strip().lower()
    if choice == 'y':
        ext_dir = zip_path.replace(".zip", "_Extracted")
        print(f"[+] Extracting to folder: {ext_dir}")
        try:
            with zipfile.ZipFile(zip_path, 'r') as z:
                z.extractall(ext_dir)
            print("[SUCCESS] Extraction complete!")
        except Exception as e:
            print(f"[-] Error during extraction: {e}")

def decrypt_ozip(filename):
    print(f"\n[+] Analyzing OZIP: {filename}")
    
    with open(filename, 'rb') as f:
        magic = f.read(12)
        if magic != b"OPPOENCRYPT!":
            print("[-] ERROR: Not a valid encrypted OZIP file.")
            return None

        f.seek(0x1050)
        test_block = f.read(16)
        
        found_key = None
        for key_hex in KEYS:
            key = bytes.fromhex(key_hex)
            ctx = AES.new(key, AES.MODE_ECB)
            decrypted_test = ctx.decrypt(test_block)
            if decrypted_test.startswith(b"PK\x03\x04"):
                found_key = key
                print(f"[SUCCESS] Decryption Key Found! (Realme X Match)")
                break
                
        if not found_key:
            print("[-] ERROR: Could not find the AES key for this firmware.")
            return None

    out_filename = filename.replace(".ozip", ".zip")
    print(f"[+] Decrypting to: {out_filename}")
    print("    This will take a few minutes. Please wait...")
    
    ctx = AES.new(found_key, AES.MODE_ECB)
    
    with open(filename, 'rb') as f_in, open(out_filename, 'wb') as f_out:
        f_in.seek(0x1050)
        
        while True:
            enc_data = f_in.read(0x4000)
            if not enc_data:
                break
            
            if len(enc_data) % 16 != 0:
                pad_len = 16 - (len(enc_data) % 16)
                padded_data = enc_data + (b'\x00' * pad_len)
                dec_data = ctx.decrypt(padded_data)[:len(enc_data)]
                f_out.write(dec_data)
            else:
                f_out.write(ctx.decrypt(enc_data))

            plain_data = f_in.read(0x4000)
            if not plain_data:
                break
            f_out.write(plain_data)

    print(f"[SUCCESS] OZIP Decrypted: {out_filename}")
    return out_filename

def main():
    print("==================================================")
    print(" ULTIMATE OZIP TOOLKIT - DECRYPT & FIRMWARE BUILDER")
    print("==================================================\n")
    
    ozip_files = [f for f in os.listdir() if f.endswith(".ozip")]
    if not ozip_files:
        print("[-] ERROR: No .ozip files found in this folder.")
        input("Press Enter to exit...")
        return
        
    for i, f in enumerate(ozip_files):
        print(f"[{i+1}] {f}")
        
    if len(ozip_files) > 1:
        try:
            choice = int(input("\nSelect file number: ")) - 1
            filename = ozip_files[choice]
        except:
            filename = ozip_files[0]
    else:
        filename = ozip_files[0]

    decrypted_zip = decrypt_ozip(filename)
    
    if decrypted_zip:
        choice_fw = input("\n[?] Do you want to generate a 'Firmware-Only' Flashable ZIP? (Y/n): ").strip().lower()
        if choice_fw != 'n':
            create_firmware_zip(decrypted_zip)
            
        extract_zip(decrypted_zip)

    print("\n================== DONE ==================")
    input("Press Enter to exit...")

if __name__ == "__main__":
    main()